### PR TITLE
add Ukrainian Bible Book Names

### PR DESCRIPTION
**Pull request by seesmof**
GOD bless you guys, have an amazingly blessed day ✝️🕊️

### CODE REVIEW

**Comment by jaanonim** [comment]
Thanks for contributing :-) . Pleace reslove conflicts, and add link to your profile in `Languages.md`.

**Comment by jaanonim** [comment]
And when you open the PR, pleace make more suitable title. "add Ukrainian Bible Book Names ✝️💞 Hallelujah thank YOU Jesus Christ our Holy Lord GOD Almighty" is a little too much, "add Ukrainian Bible Book Names" would be more than enough.

**Comment by seesmof** [comment]
GOD bless you brother, alrighty ✝️💞 can i put a link to the Bible app instead of my profile there? i wouldnt like putting my name up there. i wanna just write something like [by community for community](https://www.bible.com/uk/bible/3786/JHN.1.CUV) ✝️💝 would that be alrighty?

**Comment by jaanonim** [comment]
I know you want to bring people to God, but I would appreciate keeping some standards (if everyone wanted to link to something different, this site would be a mess). I feel like if you link your profile it will be too far from linking it to the Bible (since you have the main bible verses there) and I feel you did a good job and you should be credited for it.

**Comment by seesmof** [comment]
alrighty brother, gotcha ✝️💗 all glory goes to GOD Almighty King Jesus Christ our Lord ✝️💓 i merged those changes with Github Desktop and it somehow closed this PR. do i just open the new one?

**Pull request closed without merging**
